var _portalId = 1;
var _siteLogo = 'site_logo_small';
var _config = {
    animations: 1
};
var _tfb_cats = [
    ["TV", 1, 1],
    ["Movies", 2, 2],
    ["Music", 256, 9],
    ["News", 4, 3],
    ["Sports", 128, 8],
    ["Games", 8, 4],
    ["Social", 32, 6],
    ["Learning", 64, 7],
    ["Shopping", 512, 10],
    ["Photos", 1024, 11],
    ["Original", 16, 5]
];
var _tfb_sites = [
    ["YouTube", 19, "1.jpg", "youtube.com", "Share your videos with friends, family, and the world.", 1],
    ["Netflix", 3, "3.jpg", "netflix.com", "Netflix is the world's largest online movie rental service, with more than 11 million  subscribers.", 3],
    ["Amazon", 3, "4.jpg", "amazon.com\/Amazon-Video\/b?ie=UTF8&node=2858778011", "Watch over 50,000 of your favorite movies and hit TV shows on your TV. Instantly.", 4],
    ["Google Video", 52, "55.jpg", "video.google.com", "Search millions of videos from across the web.", 55],
    ["Facebook", 32, "7.jpg", "facebook.com", "Facebook is a social utility that connects people with friends and others who work, study and live around them.", 7],
    ["Disney Video", 9, "30.jpg", "video.disney.com", "Watch your favorite Disney videos from Disney Channel, Disney XD, movies, music videos, Disney on YouTube, and much more!", 30],
    ["TuneIn Radio", 256, "145.jpg", "tv.tunein.com", "Find streaming talk radio and streaming music radio. The best guide to every type of radio.", 145],
    ["CNN", 4, "38.jpg", "cnn.com\/videos", "CNN.com delivers the latest breaking news and information on the latest top stories, weather, business, entertainment, politics, and more.", 38],
    ["History Channel", 67, "203.jpg", "history.com", "Explore history shows, watch videos and full episodes, play games and access articles on historical topics at History.com.", 203],
    ["Pandora", 256, "49.jpg", "pandora.com", "Pandora radio is the personalized internet radio service that helps you find new music based on your old and current favorites. Create custom web radio stations, listen free.", 49],
    ["VEVO", 256, "81.jpg", "vevo.com", "Watch high quality music videos from your favorite artists for free on VEVO.", 81],
    ["Cartoon Network", 1, "73.jpg", "cartoonnetwork.com\/video", "Check out cartoons from the past, popular new cartoons, plus games for different age levels.", 73],
    ["Xfinity", 35, "133.jpg", "tv.xfinity.com", "Watch full episodes of TV shows and stream movies online free and follow the latest entertainment news on XFINITY TV by Comcast.\r\n", 133],
    ["ESPN", 128, "48.jpg", "espn.com\/video", "ESPN.com provides comprehensive sports coverage.  Complete sports information including NFL, MLB, NBA, College Football, College Basketball scores and news.", 48],    
    ["Animal Planet", 1, "65.jpg", "animalplanet.com", "Welcome to Animal Planet Video! Check out the greatest animal video on the web. Amazing kills, cute puppy dogs and more.", 65],
    ["FX", 1, "125.jpg", "fxnetworks.com", "Official site. FX Network is the home of award-winning, original television. Shows include Damages,Nip\/Tuck, Sons of Anarchy, Rescue Me, It's Always Sunny in Philadelphia, Archer, The League.", 125],
    ["Crackle", 16, "36.jpg", "crackle.com", "Crackle is a multi-platform video entertainment network and studio that distributes the hottest emerging talent on the web and beyond.", 36],
    ["National Geographic", 68, "153.jpg", "video.nationalgeographic.com", "Inspiring people to care about the planet since 1888.", 153],
    ["CBS", 1, "59.jpg", "cbs.com", "Watch CBS television online.  Find CBS primetime, daytime, late night, and classic tv episodes, videos, and information.", 59],    
    ["NBC", 1, "57.jpg", "nbc.com", "Official NBC site for primetime, daytime and late night television shows. Television (TV) network includes soap opera, reality shows and more. Find additional information on the official NBC TV site.", 57],    
    ["Fox", 1, "58.jpg", "fox.com\/full-episodes", "Full episodes and clips of your favorite Fox shows.", 58],
    ["Hulu", 3, "2.jpg", "hulu.com", "Hulu.com is a free online video service that offers hit TV shows. Currently Hulu does not allow direct playback with Kylo. Please go directly to the network sites to watch your shows until this is corrected.", 2],
    ["ABC", 1, "53.jpg", "abc.go.com\/watch-live", "Watch full episodes and shorts from your favorite ABC programs online. The official ABC video player can help you catch up if you miss a few shows.", 53],
    ["Flickr", 1056, "151.jpg", "flickr.com\/explore", "Flickr is certainly one of the best online photo management and sharing applications in the world. Show off your favorite photos and videos to the world.", 151],
    ["Fox News", 4, "91.jpg", "video.foxnews.com", "Breaking News, Latest News and Current News from FOXNews.com. Breaking news and video. Latest Current News: U.S., World, Entertainment, Health, Business, Technology, Politics, Sports.", 91],
    ["Fox Sports", 128, "46.jpg", "foxsports.com\/video", "Live scores, in-depth player and team news, sports videos, rumors, stats, schedules, fantasy games, standings for the NFL, MLB, NBA, NHL, NASCAR, NCAA Football, Basketball and more on FOX Sports.", 46],
    ["Vimeo", 16, "19.jpg", "vimeo.com", "Vimeo is a respectful community of creative people who are passionate about sharing the videos they make. We provide the best tools and highest quality video in the universe.", 19],
    ["DailyMotion", 18, "26.jpg", "dailymotion.com", "The latest music videos, short movies, tv shows, funny and extreme videos. Upload, share, and embed your videos.", 26],
    ["Pinterest", 32, "211.jpg", "pinterest.com", "Pinterest is a virtual pinboard. Pinterest allows you to organize and share all the beautiful things you find on the web.", 211],
    ["Adult Swim", 1, "74.jpg", "adultswim.com\/videos", "Watch free streaming videos of your favorite Adult Swim series, like Robot Chicken, Family Guy, Aqua Teen Hunger Force and The Boondocks on AdultSwim.com.", 74],
    ["Bravo", 1, "63.jpg", "bravotv.com\/full-episodes", "Get behind-the-scenes video, photos, blogs, and more: Bravo's reality TV and competition shows about food, style, design, beauty, and pop culture", 63],
    ["VUDU", 2, "202.jpg", "vudu.com\/movies", "Having VUDU in your home means never having to go to the video store again.", 202],
    ["NFL", 128, "99.jpg", "nfl.com\/videos", "Official site of the National Football League. It delivers in-depth team pages for all clubs, game-day coverage with real time statistics and play-by-play and chats with top players.", 99],
    ["VH1", 257, "129.jpg", "vh1.com\/full-episodes", "Watch Online Music Videos, VH1 Reality TV Show Clips & see Live Performances on VH1.com. View the Latest Movie Trailers & Pop Culture Video Clips. Tune in to VH1 TV or visit VH1.com to see the Editor.s Picks Videos Online", 129],
    ["MUBI", 2, "12.jpg", "mubi.com", "Watch the best classic, foreign and independent films, get updates from top international film festivals, share movie reviews, ratings and lists.", 12],
    ["Indieflix", 18, "14.jpg", "indieflix.com", "A site that showcases independent features. Viewers are able to buy the DVD or rent streaming video.", 14],
    ["Club Penguin", 8, "107.jpg", "www.clubpenguin.com", "Waddle around and meet new friends!", 107],
    ["Discovery", 1, "62.jpg", "discovery.com\/videos", "Discovery Channel videos that feature clips about science, technology, news, mythbusters, dirty jobs and more.", 62],
    ["TV Land", 9, "144.jpg", "tvland.com", "Official site of this classic TV station. Includes favorite shows along with retro TV commercials, theme songs, online games, and show schedules. ", 144],
    ["Syfy", 1, "67.jpg", "www.syfy.com\/episodes", "Catch full episodes of your favorite shows on Syfy.", 67],
    ["Funny Or Die", 16, "27.jpg", "funnyordie.com", "Funny Or Die is a comedy video website that combines user generated content with original, exclusive content. ", 27],
    ["ABC News", 4, "39.jpg", "abcnews.go.com\/Video", "ABC News is your breaking news resource for top stories, videos, photos, blogs, special reports and exclusive celebrity interviews on Good Morning America, World News, Nightline, 2020 and This Week with George Stephanopoulos.", 39],
];